HOST: http://www.google.com/

--- Hi5 API ---
---
Welcome to the Hi5 API!
---

--

The following is a section of resources related to the rooms
--
List all available rooms
GET /rooms
< 200
< Content-Type: application/json
{ [
{"id": 1, "name": "Together"}, {"id": 2, "name": "Create"}, {"id": 3, "name": "Engage"}, {"id": 4, "name": "Challenge"}, {"id": 5, "name": "Grow"}, {"id": 6, "name": "Talent"}, {"id": 7, "name": "Mezzanine"}
] }

